/// @file event_status.hpp
/// @brief Generated by DEXTOOL_VERSION: v0.8.3-502-ga64b2cf
/// DO NOT EDIT THIS FILE, it will be overwritten on update.
#ifndef monitored_hpp
#define monitored_hpp
#include "ops_mode-ops_state-requirer-i_ops_state_factory.hpp"
#include "ops_mode-ops_state-provider-i_ops_state_factory.hpp"
#include "testingenvironment.hpp"
#include "portenvironment.hpp"
namespace Ops_Mode {
    namespace Ops_State {
        namespace Requirer {
        } //NS:Requirer
    } //NS:Ops_State
} //NS:Foo
namespace Ops_Mode {
    namespace Ops_State {
        namespace Requirer {
        } //NS:Requirer
    } //NS:Ops_State
} //NS:Foo
#endif // monitored.hpp
