/// @file event_status.hpp
/// @brief Generated by DEXTOOL_VERSION: v0.8.3-502-ga64b2cf
/// DO NOT EDIT THIS FILE, it will be overwritten on update.
#ifndef event_status_hpp
#define event_status_hpp
#include "foo-event_status-provider-i_event_status_factory.hpp"
#include "foo-event_status-provider-i_event_status_provider.hpp"
#include "testingenvironment.hpp"
#include "portenvironment.hpp"
namespace Foo {
    namespace Event_Status {
        namespace Provider {
        } //NS:Provider
    } //NS:Event_Status
} //NS:Foo
#endif // event_status.hpp
