/// @file fuzz.hpp
/// @brief Generated by DEXTOOL_VERSION: v0.8.3-377-gc0af898
/// DO NOT EDIT THIS FILE, it will be overwritten on update.
#ifndef fuzz_hpp
#define fuzz_hpp
#include "/home/oscho707/fuzzy_testing/ip_2016_fuzzy/flat/foo-bar-provider-i_bar_provider_factory.hpp"
#include "/home/oscho707/fuzzy_testing/ip_2016_fuzzy/flat/portenvironment.hpp"
#include "/home/oscho707/fuzzy_testing/ip_2016_fuzzy/flat/foo-bar-requirer-i_bar_requirer_factory.hpp"
#include "/home/oscho707/fuzzy_testing/ip_2016_fuzzy/flat/testingenvironment.hpp"
namespace Foo {
    namespace Bar {
        namespace Provider {
        } //NS:Provider
    } //NS:Bar
} //NS:Foo
namespace Foo {
    namespace Bar {
        namespace Requirer {
        } //NS:Requirer
    } //NS:Bar
} //NS:Foo
#endif // fuzz_hpp
