/// @file fuzz.hpp
/// @brief Generated by DEXTOOL_VERSION: v0.8.3-534-g7a44f43
/// DO NOT EDIT THIS FILE, it will be overwritten on update.
#ifndef fuzz_hpp
#define fuzz_hpp
#include "foo-bar-provider-i_bar_provider_factory.hpp"
#include "foo-bar-requirer-i_bar_requirer_factory.hpp"
#include "testingenvironment.hpp"
#include "portenvironment.hpp"
namespace Foo {
    namespace Bar {
        namespace Provider {
        } //NS:Provider
    } //NS:Bar
} //NS:Foo
namespace Foo {
    namespace Bar {
        namespace Requirer {
        } //NS:Requirer
    } //NS:Bar
} //NS:Foo
#endif // fuzz_hpp
