/// @file main.hpp
/// @brief Generated by DEXTOOL_VERSION: v0.8.3-454-g8cf0044
/// DO NOT EDIT THIS FILE, it will be overwritten on update.
#ifndef main_hpp
#define main_hpp
#include "testingenvironment.hpp"
#include "portenvironment.hpp"
#include "app_main_event.hpp"
enum {
    RANDOM_GENERATOR,
    STATIC_GENERATOR,
};
#endif // main_hpp
